#!/usr/bin/env python3
"""Generate WIRE_PROTOCOL.md from the Pydantic wire models."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from types import ModuleType
from typing import Any

from pydantic import BaseModel

from cyan.core.bus import commands, events
from cyan.core.bus.envelope import EventPushEnvelope

_OUTPUT_PATH = Path(__file__).parent.parent / "WIRE_PROTOCOL.md"


# 枚举模块中指定后缀的 Pydantic wire model
def _models(module: ModuleType, suffix: str) -> list[tuple[str, type[BaseModel]]]:
    found: list[tuple[str, type[BaseModel]]] = []
    for name, value in vars(module).items():
        if (
            name.endswith(suffix)
            and isinstance(value, type)
            and issubclass(value, BaseModel)
        ):
            found.append((name, value))
    return sorted(found)


# 将 JSON Schema 字段类型压缩成人类可读字符串
def _field_type(field: dict[str, Any]) -> str:
    if "type" in field:
        return str(field["type"])
    if "anyOf" in field:
        return " | ".join(str(item.get("type", "object")) for item in field["anyOf"])
    if "$ref" in field:
        return str(field["$ref"]).rsplit("/", 1)[-1]
    return "object"


# 从一个 Pydantic model 生成字段表和完整 JSON Schema
def _model_section(name: str, model: type[BaseModel]) -> str:
    schema = model.model_json_schema()
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"### {name}", ""]
    if properties:
        lines.extend(["| Field | Type | Required |", "|---|---|---|"])
        for field_name, field in properties.items():
            lines.append(
                f"| `{field_name}` | `{_field_type(field)}` | "
                f"{'yes' if field_name in required else 'no'} |"
            )
        lines.append("")
    lines.extend(["```json", json.dumps(schema, indent=2), "```", ""])
    return "\n".join(lines)


# 生成完整协议文档并确保新增 wire model 自动进入输出
def generate() -> str:
    sections = [
        "# Wire Protocol",
        "",
        "> Generated by `scripts/gen_protocol_doc.py`. Do not edit manually.",
        "",
        "## Transport",
        "",
        "- TCP loopback `127.0.0.1:7437` (`CYAN_HOST` / `CYAN_PORT` override it).",
        "- Each frame is one newline-terminated JSON object (NDJSON).",
        "- Commands use JSON-RPC 2.0; server pushes use `kind=event`.",
        "- `event.subscribe` supports `global`, `run:<id>`, and `job:<id>` scopes.",
        "",
        "## Commands",
        "",
    ]
    for name, model in _models(commands, "Command"):
        sections.append(_model_section(name, model))
    sections.extend(["## Results", ""])
    for name, model in _models(commands, "Result"):
        sections.append(_model_section(name, model))
    sections.extend(
        [
            "## Event envelope",
            "",
            _model_section("EventPushEnvelope", EventPushEnvelope),
            "## Events",
            "",
        ]
    )
    for name, model in _models(events, "Event"):
        sections.append(_model_section(name, model))
    sections.extend(
        [
            "## Error codes",
            "",
            "| Code | Meaning |",
            "|---|---|",
            "| `-32700` | Parse error |",
            "| `-32600` | Invalid JSON-RPC request |",
            "| `-32601` | Method not found |",
            "| `-32602` | Invalid params |",
            "| `-32603` | Internal error |",
            "| `-32010` | Session not found |",
            "| `-32011` | Session closed |",
            "| `-32012` | Session busy |",
            "| `-32030` | Job not found |",
            "| `-32031` | Incident decision failed |",
            "| `-32032` | Core is shutting down |",
            "",
        ]
    )
    return "\n".join(sections)


# 写入协议文档，或在 --check 模式验证当前文件与模型同源
def main() -> None:
    parser = argparse.ArgumentParser(description="Generate WIRE_PROTOCOL.md")
    parser.add_argument("--check", action="store_true", help="Verify generated output")
    parser.add_argument("--output", default=str(_OUTPUT_PATH))
    args = parser.parse_args()
    output_path = Path(args.output)
    content = generate()
    if args.check:
        if not output_path.exists() or output_path.read_text(encoding="utf-8") != content:
            print(f"ERROR: {output_path} is out of sync", file=sys.stderr)
            raise SystemExit(1)
        print(f"OK: {output_path} is up to date.")
        return
    output_path.write_text(content, encoding="utf-8")
    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
